---
title: "Bootstrapping"
output: github_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages.

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)

set.seed(1)
```


## Generate a relevant example


```{r}
n_samp = 250

sim_df_const =
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst =
  sim_df_const |> 
  mutate(
    error = error * .75 * x,
    y = 2 + 3 * x + error
  )

sim_df_const |> 
  ggplot(aes(x = x, y = y)) + geom_point()

sim_df_nonconst |> 
  ggplot(aes(x = x, y = y)) + geom_point()

```


fit some linear models

```{r}
sim_df_const |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()

sim_df_nonconst |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()
```



